// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfxW7UwJgjfwxFmeRZBBS63bmvEW4UMx4',
    appId: '1:44230927846:android:5ddc166858465338b92227',
    messagingSenderId: '44230927846',
    projectId: 'carwash-592e8',
    storageBucket: 'carwash-592e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsSHt6aKg-JFFMOHMPKYJ5RVQSAUE5o2c',
    appId: '1:44230927846:ios:f45751c5d702e9e9b92227',
    messagingSenderId: '44230927846',
    projectId: 'carwash-592e8',
    storageBucket: 'carwash-592e8.firebasestorage.app',
    iosBundleId: 'com.carwash.user',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2K4o4QCvN5NACJO3fAt4luX3TPxyChvc',
    appId: '1:44230927846:web:dfe49d93185efbd7b92227',
    messagingSenderId: '44230927846',
    projectId: 'carwash-592e8',
    authDomain: 'carwash-592e8.firebaseapp.com',
    storageBucket: 'carwash-592e8.firebasestorage.app',
    measurementId: 'G-D9C4M6XTLV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsSHt6aKg-JFFMOHMPKYJ5RVQSAUE5o2c',
    appId: '1:44230927846:ios:70ddfe3f34eb45a5b92227',
    messagingSenderId: '44230927846',
    projectId: 'carwash-592e8',
    storageBucket: 'carwash-592e8.firebasestorage.app',
    iosBundleId: 'com.example.carWashLight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2K4o4QCvN5NACJO3fAt4luX3TPxyChvc',
    appId: '1:44230927846:web:aea3f60a9040a463b92227',
    messagingSenderId: '44230927846',
    projectId: 'carwash-592e8',
    authDomain: 'carwash-592e8.firebaseapp.com',
    storageBucket: 'carwash-592e8.firebasestorage.app',
    measurementId: 'G-V7ERT8ZVS0',
  );

}